<a href="https://colab.research.google.com/github/LaibaNaheed/All-in-One-Python-Practice-Notebook-NumPy/blob/main/All-in-One-Python-Practice-Notebook-NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*LAB MANUALS*
* LAIBA NAHEED
* FA23-BSCS-346

LAB TASK 5:

4.Creating Arrays with Numpy:

In [ ]:
import numpy as np

# i. Print the array [1, 2, 3, 4, 5] and its datatype
arr1 = np.array([1, 2, 3, 4, 5])
print("Array:", arr1)
print("Datatype:", arr1.dtype)

# ii. Use a tuple to create a NumPy array
arr_tuple = np.array((10, 20, 30))
print("\nArray from tuple:", arr_tuple)

# iii. Print 0-D array
arr_0d = np.array(42)
print("\n0-D array:", arr_0d)

# iv. Print 1-D array
arr_1d = np.array([1, 2, 3, 4])
print("\n1-D array:", arr_1d)

# v. Print 2-D array
arr_2d = np.array([[1, 2], [3, 4]])
print("\n2-D array:\n", arr_2d)

# vi. Print 3-D array
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("\n3-D array:\n", arr_3d)

# vii. Print N-D array (example 4-D)
arr_nd = np.array([[[[1, 2], [3, 4]]]])
print("\nN-D array:\n", arr_nd)

Array: [1 2 3 4 5]
Datatype: int64

Array from tuple: [10 20 30]

0-D array: 42

1-D array: [1 2 3 4]

2-D array:
 [[1 2]
 [3 4]]

3-D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

N-D array:
 [[[[1 2]
   [3 4]]]]


5.Array Attributes:

In [ ]:
import numpy as np

# i. Print an array of evenly spaced numbers up to 24
# Example: from 0 to 24 (inclusive) with step 1
arr_even = np.arange(0, 25, 1)
print("Array of evenly spaced numbers up to 24:")
print(arr_even)

# ii. Print the size (shape) of 2-D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nShape of 2-D array:", arr_2d.shape)  # (rows, columns)

# iii. Print the total number of elements using ndarray.size
print("Total elements in 2-D array:", arr_2d.size)

# iv. Print the datatype of 2-D array
print("Datatype of 2-D array:", arr_2d.dtype)

# v. Print the itemsize (size of one element in bytes)
print("Item size of 2-D array:", arr_2d.itemsize, "bytes")

Array of evenly spaced numbers up to 24:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

Shape of 2-D array: (2, 3)
Total elements in 2-D array: 6
Datatype of 2-D array: int64
Item size of 2-D array: 8 bytes


6.Array Indexing:

In [ ]:

import numpy as np

# Example 2-D array for i, ii, iii
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

# i. Print 2nd element on 1st dim (first row, index 1)
print("2nd element of 1st row:", arr[0, 1])

# ii. Print 5th element on 2nd dim (second row, index 4)
print("5th element of 2nd row:", arr[1, 4])

# iii. Access the third element of the second array of the first array
# Interpreted as: arr[0][1][2] for 3D? But arr is 2D, so assuming arr[1,2]
print("Third element of second row:", arr[1, 2])

# iv. 1D array indexing with positive and negative indices
arr_1d = np.arange(1, 10)  # [1,2,3,...,9]
print("1D array:", arr_1d)

# Positive indexing (e.g., elements 2, 4, 6)
positive_indexed = arr_1d[[1, 3, 5]]  # indices 1,3,5
print("Selected elements using positive indexing:", positive_indexed)

# Negative indexing (e.g., last, second last, third last)
negative_indexed = arr_1d[[-1, -2, -3]]
print("Selected elements using negative indexing:", negative_indexed)

# v. 2D array with two rows, retrieve last element of second row
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
last_element_second_row = arr_2d[1, -1]  # second row, last element
print("Last element of second row:", last_element_second_row)

2nd element of 1st row: 2
5th element of 2nd row: 10
Third element of second row: 8
1D array: [1 2 3 4 5 6 7 8 9]
Selected elements using positive indexing: [2 4 6]
Selected elements using negative indexing: [9 8 7]
Last element of second row: 60


7.Numpy Slicing Arrays:

In [ ]:

import numpy as np

# Arrange elements from 0 to 19
arr = np.arange(20)
print("Array from 0 to 19:", arr)

# Elements from 10 to 19
print("Elements 10 to 19:", arr[10:20])  # or arr[10:]

# iii. Slice elements from index 1 to 5 (1 included, 5 excluded)
print("Elements from index 1 to 5:", arr[1:5])

# iv. Slice from index 3 from end to index 1 from end
print("Elements from -3 to -1:", arr[-3:-1])  # -3 included, -1 excluded

# v. Slice from beginning to index 4
print("Elements from start to index 4:", arr[:5])

# vi. Slice from index 4 to end
print("vi. Elements from index 4 to end:", arr[4:])

# vii. Return every other element from index 1 to 5
print("vii. Every other element from index 1 to 5:", arr[1:5:2])

# viii. Return every other element from entire array
print("viii. Every other element of entire array:", arr[::2])

# --- 2-D Array Examples ---
arr2d = np.array([[10, 20, 30, 40, 50],
                  [60, 70, 80, 90, 100]])

# ix. Slice 2-D array from second row (index 1), elements index 1 to 4
print("ix. 2D slice second row, index 1 to 4:", arr2d[1, 1:4])

# x. Slice 2-D array, both rows, index 2 column
print("x. Column index 2 of both rows:", arr2d[:, 2])

# xi. Slice 2-D array, both rows, columns index 1 to 4 → returns 2D array
print("xi. Both rows, columns 1 to 4:\n", arr2d[:, 1:4])

# xii. Multi-dimensional ndarray
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print("xii. Multi-dimensional ndarray:\n", arr3d)

# xiii. Slice single element in array (e.g., first element of first row)
print("xiii. Single element arr2d[0,0]:", arr2d[0,0])

i. Array from 0 to 19: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
ii. Elements 10 to 19: [10 11 12 13 14 15 16 17 18 19]
iii. Elements from index 1 to 5: [1 2 3 4]
iv. Elements from -3 to -1: [17 18]
v. Elements from start to index 4: [0 1 2 3 4]
vi. Elements from index 4 to end: [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
vii. Every other element from index 1 to 5: [1 3]
viii. Every other element of entire array: [ 0  2  4  6  8 10 12 14 16 18]
ix. 2D slice second row, index 1 to 4: [70 80 90]
x. Column index 2 of both rows: [30 80]
xi. Both rows, columns 1 to 4:
 [[20 30 40]
 [70 80 90]]
xii. Multi-dimensional ndarray:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
xiii. Single element arr2d[0,0]: 10


8. Arrange elements 0 to 19 using numpy

In [ ]:
import numpy as np

arr = np.arange(20)
print("Array 0–19:", arr)

# ii. Print elements from 10 to 19
print("10 to 19:", arr[10:20])

# iii. Slice index 1 to index 5
print("1 to 5:", arr[1:6])

# iv. Slice from 3rd last to 1st last (-3 to -1)
print("3rd last to last:", arr[-3:-1])

# v. Beginning to index 4
print("Start to 4:", arr[:5])

# vi. Index 4 to end
print("4 to end:", arr[4:])

# vii. Every other element (step 2) from index 1 to 5
print("Every other element 1–5:", arr[1:6:2])

# viii. Every other element entire array (step 2)
print("Every other element whole array:", arr[::2])

# ---------------------------------------------
# 2. 2D ARRAY SLICING
# ---------------------------------------------
arr2d = np.array([
    [10, 20, 30, 40, 50],
    [60, 70, 80, 90, 100]
])

# ix. Slice from second row → index 1 to 4
print("2D slice row2, 1–4:", arr2d[1, 1:4])

# x. Slice both rows, return index 2 (3rd column)
print("Both rows, index 2:", arr2d[:, 2])

# xi. Slice both rows, index 1 to 4 → returns 2D
print("Both rows, 1–4:", arr2d[:, 1:4])

# xii. Print multi-dimensional ndarray
print("Multi-dimensional array:\n", arr2d)

# xiii. Slice single element (row1, col3)
print("Single element arr2d[0,2]:", arr2d[0, 2])



Array 0–19: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
10 to 19: [10 11 12 13 14 15 16 17 18 19]
1 to 5: [1 2 3 4 5]
3rd last to last: [17 18]
Start to 4: [0 1 2 3 4]
4 to end: [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Every other element 1–5: [1 3 5]
Every other element whole array: [ 0  2  4  6  8 10 12 14 16 18]
2D slice row2, 1–4: [70 80 90]
Both rows, index 2: [30 80]
Both rows, 1–4: [[20 30 40]
 [70 80 90]]
Multi-dimensional array:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
Single element arr2d[0,2]: 30


9. ARRAY CREATION ROUTINES

In [ ]:

# i. Zeros array
print("Zeros:\n", np.zeros((3,3)))

# ii. Ones array
print("Ones:\n", np.ones((3,3)))

# iii. Identity matrix (diagonal ones)
print("Diagonal ones:\n", np.eye(4))

# iv. Using numpy.identity()
print("Identity (numpy.identity):\n", np.identity(4))

# v. Array with range
print("Range array:", np.arange(5, 50, 5))

# vi. Interpret input as a matrix
print("Matrix:\n", np.matrix([[1,2],[3,4]]))

# vii. Convert sequence to ndarray
print("Converted ndarray:", np.array([1,2,3,4]))



NameError: name 'np' is not defined

9. NUMPY ARITHMETIC OPERATIONS

In [ ]:

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# i. Addition (operator)
print("Add operator:", a + b)

# ii. Addition (numpy function)
print("Add function:", np.add(a, b))

# iii. Subtraction (operator)
print("Subtract operator:", a - b)

# iv. Subtraction (numpy function)
print("Subtract function:", np.subtract(a, b))

# v. Multiplication (operator)
print("Multiply operator:", a * b)

# vi. Multiplication (function)
print("Multiply function:", np.multiply(a, b))

# vii. Division (operator)
print("Divide operator:", a / b)

# viii. Division (function)
print("Divide function:", np.divide(a, b))

# ix. Modulus
print("Modulus:", np.mod(a, b))

# x. Remainder
print("Remainder:", np.remainder(a, b))

# xi. Mean
print("Mean of a:", np.mean(a))

# xii. Average
print("Average:", np.average(a))

# xiii. Sum
print("Sum:", np.sum(a))

# xiv. Variance
print("Variance:", np.var(a))

# xv. Power (a^b)
print("Power:", np.power(a, b))

# xvi. Maximum
print("Max:", np.max(a))

# xvii. Median
print("Median:", np.median(a))

# xviii. Minimum
print("Min:", np.min(a))

# xix. Percentile (50th = median)
print("Percentile 50%:", np.percentile(a, 50))

# xx. Standard deviation
print("Std Dev:", np.std(a))

# xxi. Harmonic mean
print("Harmonic Mean:", len(a) / np.sum(1/a))

Add operator: [11 22 33]
Add function: [11 22 33]
Subtract operator: [ 9 18 27]
Subtract function: [ 9 18 27]
Multiply operator: [10 40 90]
Multiply function: [10 40 90]
Divide operator: [10. 10. 10.]
Divide function: [10. 10. 10.]
Modulus: [0 0 0]
Remainder: [0 0 0]
Mean of a: 20.0
Average: 20.0
Sum: 60
Variance: 66.66666666666667
Power: [   10   400 27000]
Max: 30
Median: 20.0
Min: 10
Percentile 50%: 20.0
Std Dev: 8.16496580927726
Harmonic Mean: 16.363636363636363


Thank You!